### ISSUE TITLE
Lets get started on voice channel functionality

### ISSUE THREAD

**Issue by Worthy-Alpaca** [rik079/Speasier#29]
we may need to use discord.py[audio] here, not sure

**Comment by rik079** [comment]
I assume that this project will consist of the following parts:

- Writing the code to get the audio files from AWS Polly
- Building the part that makes the bot play those files in the voice channel
- Creating a database in RAM to (hopefully) reduce the time to check what voice belongs to who
- Finding a way to deal with storing and deleting the audio files.

Given that you already started with nr. 2, shall we divide the tasks so that I'll take care of points 1 and 3, while you look at 2 and 4? (we can always change this later of course)

**Comment by rik079** [comment]
This is now being taken care of by the AWS Polly project
